extends:
  - 'airbnb-base'
  - 'airbnb-typescript'
  - 'prettier'
  - 'plugin:solid/recommended'
  - 'plugin:import/typescript'
plugins:
  - '@typescript-eslint'
  - 'prettier'
  - 'solid'
env:
globals:
rules:
  'prettier/prettier': 'error'
  'react/jsx-filename-extension': 0
parserOptions:
  project: './tsconfig.json'
  parser: '@typescript-eslint/parser'
