name: Test Backend

on:
  push:
  workflow_dispatch:

jobs:
  Test_Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - name: Install deps
        run: |
          cd ./packages/backend
          pnpm i
          go mod download
          go install github.com/onsi/ginkgo/v2/ginkgo
      - name: Install and start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
      - name: Run integration test
        run: pnpm test:backend
